package controlling.contractRegister.dic;

public enum CustomerAddressCountry {

    PL("Polska"),
    AF("Afganistan"),
    AL("Albania"),
    DZ("Algieria"),
    AD("Andora"),
    AO("Angola"),
    AI("Anguilla"),
    AQ("Antarktyda"),
    AG("Antigua i Barbuda"),
    SA("Arabia Saudyjska"),
    AR("Argentyna"),
    AM("Armenia"),
    AW("Aruba"),
    AU("Australia"),
    AT("Austria"),
    AZ("Azerbejdżan"),
    BS("Bahamy"),
    BH("Bahrajn"),
    BD("Bangladesz"),
    BB("Barbados"),
    BE("Belgia"),
    BZ("Belize"),
    BJ("Benin"),
    BM("Bermudy"),
    BT("Bhutan"),
    BY("Białoruś"),
    BO("Boliwia"),
    BQ("Bonaire, Sint Eustatius i Saba"),
    BA("Bośnia i Hercegowina"),
    BW("Botswana"),
    BR("Brazylia"),
    BN("Brunei Darussalam"),
    IO("Brytyjskie Terytorium Oceanu Indyjskiego"),
    BG("Bułgaria"),
    BF("Burkina Faso"),
    BI("Burundi"),
    XC("Ceuta"),
    CL("Chile"),
    CN("Chiny"),
    CW("Curaçao"),
    HR("Chorwacja"),
    CY("Cypr"),
    TD("Czad"),
    ME("Czarnogóra"),
    CZ("Czechy"),
    DK("Dania"),
    DM("Dominika"),
    DO("Dominikana"),
    DJ("Dżibuti"),
    EG("Egipt"),
    EC("Ekwador"),
    ER("Erytrea"),
    EE("Estonia"),
    ET("Etiopia"),
    FK("Falklandy"),
    FJ("Fidżi Republika"),
    PH("Filipiny"),
    FI("Finlandia"),
    TF("Francuskie Terytorium Południowe"),
    FR("Francja"),
    GA("Gabon"),
    GM("Gambia"),
    GH("Ghana"),
    GI("Gibraltar"),
    GR("Grecja"),
    GD("Grenada"),
    GL("Grenlandia"),
    GE("Gruzja"),
    GU("Guam"),
    GY("Gujana"),
    GT("Gwatemala"),
    GN("Gwinea"),
    GQ("Gwinea Równikowa"),
    GW("Gwinea-Bissau"),
    HT("Haiti"),
    ES("Hiszpania"),
    HN("Honduras"),
    HK("Hongkong"),
    IN("Indie"),
    ID("Indonezja"),
    IQ("Irak"),
    IR("Iran"),
    IE("Irlandia"),
    IS("Islandia"),
    IL("Izrael"),
    JM("Jamajka"),
    JP("Japonia"),
    YE("Jemen"),
    JO("Jordania"),
    KY("Kajmany"),
    KH("Kambodża"),
    CM("Kamerun"),
    CA("Kanada"),
    QA("Katar"),
    KZ("Kazachstan"),
    KE("Kenia"),
    KG("Kirgistan"),
    KI("Kiribati"),
    CO("Kolumbia"),
    KM("Komory"),
    CG("Kongo"),
    CD("Kongo, Republika Demokratyczna"),
    KP("Koreańska Republika Ludowo-Demokratyczna"),
    XK("Kosowo"),
    CR("Kostaryka"),
    CU("Kuba"),
    KW("Kuwejt"),
    LA("Laos"),
    LS("Lesotho"),
    LB("Liban"),
    LR("Liberia"),
    LY("Libia"),
    LI("Liechtenstein"),
    LT("Litwa"),
    LU("Luksemburg"),
    LV("Łotwa"),
    MK("Macedonia Północna"),
    MG("Madagaskar"),
    YT("Majotta"),
    MO("Makau"),
    MW("Malawi"),
    MV("Malediwy"),
    MY("Malezja"),
    ML("Mali"),
    MT("Malta"),
    MP("Mariany Północne"),
    MA("Maroko"),
    MR("Mauretania"),
    MU("Mauritius"),
    MX("Meksyk"),
    XL("Melilla"),
    FM("Mikronezja"),
    UM("Minor (Powiernicze Wyspy Pacyfiku Stanów Zjednoczonych)"),
    MD("Mołdawia"),
    MN("Mongolia"),
    MS("Montserrat"),
    MZ("Mozambik"),
    MM("Myanmar (Burma)"),
    NA("Namibia"),
    NR("Nauru"),
    NP("Nepal"),
    NL("Niderlandy"),
    DE("Niemcy"),
    NE("Niger"),
    NG("Nigeria"),
    NI("Nikaragua"),
    NU("Niue"),
    NF("Norfolk"),
    NO("Norwegia"),
    NC("Nowa Kaledonia"),
    NZ("Nowa Zelandia"),
    PS("Okupowane Terytorium Palestyny"),
    OM("Oman"),
    PK("Pakistan"),
    PW("Palau"),
    PA("Panama"),
    PG("Papua Nowa Gwinea"),
    PY("Paragwaj"),
    PE("Peru"),
    PN("Pitcairn"),
    PF("Polinezja Francuska"),
    ZA("Południowa Afryka"),
    GS("Południowa Georgia i Południowe Wyspy Sandwich"),
    PT("Portugalia"),
    KR("Republika Korei"),
    CF("Rep.Środkowoafryańska"),
    RU("Rosja"),
    RW("Rwanda"),
    EH("Sahara Zachodnia"),
    BL("Saint Barthelemy"),
    RO("Rumunia"),
    SV("Salwador"),
    WS("Samoa"),
    AS("Samoa Amerykańskie"),
    SM("San Marino"),
    SN("Senegal"),
    XS("Serbia"),
    SC("Seszele"),
    SL("Sierra Leone"),
    SG("Singapur"),
    SZ("Suazi"),
    SK("Słowacja"),
    SI("Słowenia"),
    SO("Somalia"),
    LK("Sri Lanka"),
    PM("St. Pierre i Miquelon"),
    KN("St.Kitts i Nevis"),
    LC("St.Lucia"),
    VC("St.Vincent i Grenadyny"),
    US("Stany Zjedn. Ameryki"),
    SD("Sudan"),
    SS("Sudan Południowy"),
    SR("Surinam"),
    SY("Syria"),
    CH("Szwajcaria"),
    SE("Szwecja"),
    SH("Święta Helena"),
    TJ("Tadżykistan"),
    TH("Tajlandia"),
    TW("Tajwan"),
    TZ("Tanzania"),
    TG("Togo"),
    TK("Tokelau"),
    TO("Tonga"),
    TT("Trynidad i Tobago"),
    TN("Tunezja"),
    TR("Turcja"),
    TM("Turkmenistan"),
    TC("Wyspy Turks i Caicos"),
    TV("Tuvalu"),
    UG("Uganda"),
    UA("Ukraina"),
    UY("Urugwaj"),
    UZ("Uzbekistan"),
    VU("Vanuatu"),
    WF("Wallis i Futuna"),
    VA("Watykan"),
    VE("Wenezuela"),
    HU("Węgry"),
    GB("Wielka Brytania"),
    VN("Wietnam"),
    IT("Włochy"),
    TL("Wschodni Timor"),
    CI("Wyb.Kości Słoniowej"),
    BV("Wyspa Bouveta"),
    CX("Wyspa Bożego Narodzenia"),
    CK("Wyspy Cooka"),
    VI("Wyspy Dziewicze-USA"),
    VG("Wyspy Dziewicze-W.B"),
    HM("Wyspy Heard i McDonald"),
    CC("Wyspy Kokosowe (Keelinga)"),
    FO("Wyspy Owcze"),
    MH("Wyspy Marshalla"),
    SB("Wyspy Salomona"),
    SX("Wyspa Sint Maarten (część holenderska wyspy)"),
    ST("Wyspy Św.Tomasza i Książęca"),
    ZM("Zambia"),
    CV("Zielony Przylądek"),
    ZW("Zimbabwe"),
    AE("Zjedn.Emiraty Arabskie"),
    XI("Zjednoczone Królestwo (Irlandia Północna)");

    private final String name;

    CustomerAddressCountry(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}